CORE_TASTES: dict[str, list[str]] = {
    "weight": [
        "heavy",
        "cassoulet",
        "cassoulet",
        "full_bodied",
        "thick",
        "milk",
        "fat",
        "mincemeat",
        "steak",
        "bold",
        "pizza",
        "pasta",
        "creamy",
        "bread",
    ],
    "sweet": ["sweet", "sugar", "cake", "mango", "stevia"],
    "acid": ["acid", "sour", "vinegar", "yoghurt", "cevich", "cevich"],
    "salt": [
        "salty",
        "salty",
        "parmesan",
        "oyster",
        "pizza",
        "bacon",
        "cured_meat",
        "sausage",
        "potato_chip",
    ],
    "piquant": ["spicy"],
    "fat": [
        "fat",
        "fried",
        "creamy",
        "cassoulet",
        "foie_gras",
        "buttery",
        "cake",
        "foie_gras",
        "sausage",
        "brie",
        "carbonara",
    ],
    "bitter": ["bitter", "kale"],
}
