VARIETY_MAPPING = {
    "Shiraz": "Syrah",
    "Pinot Gris": "Pinot Grigio",
    "Pinot Grigio/Gris": "Pinot Grigio",
    "Garnacha, Grenache": "Grenache",
    "Garnacha": "Grenache",
    "CarmenÃ¨re": "Carmenere",
    "GrÃ¼ner Veltliner": "Gruner Veltliner",
    "TorrontÃ©s": "Torrontes",
    "RhÃ´ne-style Red Blend": "Rhone-style Red Blend",
    "AlbariÃ±o": "Albarino",
    "GewÃ¼rztraminer": "Gewurztraminer",
    "RhÃ´ne-style White Blend": "Rhone-style White Blend",
    "SpÃƒÂ¤tburgunder, Pinot Noir": "Pinot Noir",
    "Sauvignon, Sauvignon Blanc": "Sauvignon Blanc",
    "Pinot Nero, Pinot Noir": "Pinot Noir",
    "Malbec-Merlot, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Meritage, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Garnacha, Grenache": "Grenache",
    "FumÃ© Blanc": "Sauvignon Blanc",
    "Cabernet Sauvignon-Cabernet Franc, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Cabernet Merlot, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Cabernet Sauvignon-Merlot, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Cabernet Blend, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Malbec-Cabernet Sauvignon, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Merlot-Cabernet Franc, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Merlot-Cabernet Sauvignon, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Cabernet Franc-Merlot, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Merlot-Malbec, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Cabernet, Bordeaux-style Red Blend": "Bordeaux-style Red Blend",
    "Primitivo, Zinfandel": "Zinfandel",
    "AragonÃªs, Tempranillo": "Aragonez, Tempranillo",
}

CORE_DESCRIPTORS = [
    "aroma",
    "weight",
    "sweet",
    "acid",
    "salt",
    "piquant",
    "fat",
    "bitter",
]
